apps/core/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import ajaxify

from .views import ContactUsView

admin.autodiscover()

urlpatterns = patterns('core.urls',
    url(r'^$',
        TemplateView.as_view(template_name='home.html'),
        name='home_main'),
    url(r'^getting-started/',
        TemplateView.as_view(template_name='getting-started.html'),
        name='home_getting-started'),
    url(r'^author-info/',
        TemplateView.as_view(template_name='author-info.html'),
        name='home_author-info'),
    url(r'^contact-us/',
        login_required(ContactUsView),
        name='home_contact-us'),
    url(r'^do-anything/',
        TemplateView.as_view(template_name='do-anything.html'),
        name='home_do-anything'),
    url(r'^register/',
        TemplateView.as_view(template_name='register.html'),
        name='home_register'),

    # Account registration and authentication
    url(r'^accounts/', include('allauth.urls')),
    # Instructors
    url(r'^users/', include('users.urls')),
    # Courses and programs
    url(r'^habitgrams/', include('programs.urls')),
    # Habitgrams
    #url(r'^habitgrams/', include('habitgrams.urls')),
)


# Default routes
urlpatterns += patterns('',
    # Serve media files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    
    
    # Admin docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Admin:
    url(r'^admin/', include(admin.site.urls)),

    # ajaxify urls
    url(ajaxify.config.ajaxify_url, include('ajaxify.urls')),
)

apps/programs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


from .views import (ProgramListView, ProgramAuthListView, ProgramDetailView,
                    ProgramSubscribeView, SubscriptionListView,
                    ProgramCreateView, ProgramUpdateView,
                    program_unsubscribe, SubscriptionUpdateView)

urlpatterns = patterns('',
    url(r'^$', ProgramListView.as_view(), name='program-list'),
    url(r'^subscribed/$', login_required(SubscriptionListView.as_view()), name='program-sub-list'),
    url(r'^authored/$', login_required(ProgramAuthListView.as_view()), name='program-auth-list'),
    url(r'^(?P<pk>\d+)/$', ProgramDetailView.as_view(), name='program-detail'),
    url(r'^create/$', login_required(ProgramCreateView.as_view()), name='program-create'),
    url(r'^edit/(?P<pk>\d+)/$', login_required(ProgramUpdateView.as_view()), name='program-update'),
    url(r'^subscribe/(?P<pk>\d+)/$', login_required(ProgramSubscribeView.as_view()), name='program-subscribe'),
    url(r'^subscription/edit/(?P<pk>\d+)/$', login_required(SubscriptionUpdateView.as_view()), name='program-sub-update'),
    url(r'^unsubscribe/(?P<pk>\d+)/$', login_required(program_unsubscribe), name='program-unsubscribe'),
)

apps/programs/models.py
# courses/models.py

from datetime import datetime
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.utils.text import slugify
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

import recurly

from twilio.rest import TwilioRestClient
from core.models import TimeStampedModel
from core.utils import CURRENCIES, SUBSCRIPTION_PLAN, HABITGRAM_TYPES, SCHEDULE_OPTIONS
from users.models import (HabitgramUser, BillingInfo)

User = get_user_model()

twilio_client = TwilioRestClient(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)

RECURLY_SMS_PLAN_CODE = 'habitgram_sms_service'
RECURLY_VOICEMAIL_PLAN_CODE = 'habitgram_voicemail_service'

class Habitgram(TimeStampedModel):
    """
       An habitgram class specifying the details of communication with a 
       subscriber
    """

    title = models.CharField(default='', max_length=255)
    description = models.TextField(default='', null=True, blank=True)
    image = models.ImageField(upload_to='images_programs', null=True, blank=True)
    duration = models.CharField(default='',
                                max_length=255)
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=255,
                                choices=CURRENCIES,
                                default=CURRENCIES[0])
    subscription_plan = models.CharField(max_length=255,
                                      choices=SUBSCRIPTION_PLAN,
                                      default=SUBSCRIPTION_PLAN[0])
    author = models.ForeignKey(HabitgramUser)
    is_active = models.NullBooleanField(default=True)
    message_type = models.CharField(default='EML', max_length=3, choices=HABITGRAM_TYPES)
    message = models.TextField(default='')
    
    def get_recurly_plan_code(self):
        text = '%(id)s-%(title)s' % {'id': str(self.id),
                                     'title': self.title}
        return slugify(text)
    
    def get_absolute_url(self):
        return reverse('program-detail', args=[str(self.id)])
    
    def get_subscription_url(self):
        return reverse('program-subscribe', args=[str(self.id)])
    
    def get_share_url(self):
        return reverse('program-share', args=[str(self.id)])
    
    def delete(self, *args, **kwargs):
        Habitgram.objects.filter(content_type=ContentType.objects.get_for_model(Program),
                                 object_id=self.id).delete()
        super(Program, self).delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        if settings.RECURLY_ONLINE:
            # Save in / update Recurly after saving, if in online mode
            try:
                plan = recurly.Plan.get(self.get_recurly_plan_code())
            except recurly.NotFoundError:
                plan = recurly.Plan(plan_code=self.get_recurly_plan_code())
            plan.name = self.title
            plan.description = self.description
            price_in_cents = int(self.price) * 100
            plan.unit_amount_in_cents = recurly.Money(USD=price_in_cents)
            interval_unit = self.subscription_plan.split(' ')[-1].replace("')", "")
            plan.plan_interval_unit = '%(interval)ss' % {'interval': interval_unit}
            plan.save()

            # Create a recurly subscription  based on the type of habitgram created
            if self.message_type in ('SMS', 'VML'):
                subscription = recurly.Subscription()
                try:
                    billing_info = BillingInfo.objects.get(user=self.content_object.author.user)
                except BillingInfo.DoesNotExist:
                    raise ValidationError('Please enter your billing information')
                try:
                    if self.message_type == 'SMS':
                        subscription.plan_code = RECURLY_SMS_PLAN_CODE
                    elif self.message_type == 'VML':
                        subscription.plan_code = RECURLY_VOICEMAIL_PLAN_CODE
                except recurly.NotFoundError, e:
                    raise ValidationError('Server error: %s\nPlease contact the administrator in the contact page.' % e)
                subscription.currency = self.content_object.currency
                account = recurly.Account.get(self.content_object.author.get_recurly_account_code())
                try:
                    subscription.account = account
                    try:
                        subscription.save()
                    except recurly.ValidationError, e:
                        if e in ['already_subscribed: subscription.base You already have a subscription to this plan.']:
                            super(Subscription, self).save(*args, **kwargs)
                            return
                except recurly.BadRequestError, e:
                    raise ValidationError('Server error: %s\nPlease contact the administrator in the contact page.' % e)
        return super(Habitgram, self).save(*args, **kwargs)
#       self.send()

    
    def send(self, subscriber):
        """Send a habitgram based on the message type"""
        
        if subscriber == None: raise ValidationError('Subscriber cannot be None')
        
        from_author = self.author
        
        if str(self.message_type) == 'EML':
            subject = '%(subject)s' % {'subject': self}
            message = '%(message)s' % {'message': self.message}
            from_email = '%(from_email)s' % {'from_email': from_author.user.email}
            to_email = '%(to_email)s' % {'to_email': subscriber.user.email}
            send_mail(subject,
                      message,
                      from_email,
                      [to_email],
                      fail_silently=False)
        
        elif str(self.message_type) == 'SMS':
            if from_author.phone_number == '':
                from_author.phone_number = settings.TWILIO_DEFAULT_CALLERID
            twilio_client.sms.messages.create(
                body=self.message,
                to='+14172555504', # Replace with your phone number
#                from_=from_author.phone_number # Replace with your Twilio number
                from_=settings.TWILIO_DEFAULT_CALLERID # Replace with your Twilio number
            )
        
        elif str(self.message_type) == 'VML':
            message_cleaned = self.message.replace(' ', '%20')
            twilio_client.calls.create(
                to="+14172555504", # Any phone number
                from_=settings.TWILIO_DEFAULT_CALLERID, # Must be a valid Twilio number
                url="http://twimlets.com/message?Message=%s" % message_cleaned
            )
        else:
            raise ValidationError('Select a valid habitgram type: %s' % self.message_type)

    def __unicode__(self):
        return '%(habitgram)s - (%(message_type)s)' % \
            {'habitgram': self.title,
             'message_type': self.message_type}
    
    # Add the custom manager
    class Meta:
        class _Manager(models.Manager):
            use_for_related_fields = True
            
            def past(self, **kwargs):
                return self.filter(schedule__lte=datetime.now(), **kwargs)
            
            def future(self, **kwargs):
                return self.filter(schedule__gte=datetime.now(), **kwargs)

            def recent(self, **kwargs):
                return self.filter(is_active=True, **kwargs).order_by('-created')
    objects = Meta._Manager()


class Subscription(TimeStampedModel):
    """
       A class to store a program which a user can subscribe to
    """
    habitgram = models.ForeignKey(Habitgram, default=1, null=False, blank=False)
    subscriber = models.ForeignKey(HabitgramUser, default=1, null=False, blank=False)
    program_completed = models.NullBooleanField(default=False)
    coupon_code = models.CharField(default='', max_length=255)
    price = models.DecimalField(default=0.00, max_digits=8, decimal_places=2)
    currency = models.CharField(max_length=255, choices=CURRENCIES, default=CURRENCIES[0])
    quantity = models.IntegerField(default=1)
    total_billing_cycles = models.IntegerField(default=0)
    trial_ends_at = models.DateField(default=datetime.today().date)
    starts_at = models.DateField(default=datetime.today().date)
    first_renewal_date = models.DateField(default=datetime.today().date)

    def save(self, *args, **kwargs):
        if settings.RECURLY_ONLINE:
            subscription = recurly.Subscription()
            try:
                billing_info = BillingInfo.objects.get(user=self.subscriber.user)
            except BillingInfo.DoesNotExist:
                raise ValidationError('Please enter your billing information')
            try:
                subscription.plan_code = self.program.get_recurly_plan_code()
            except recurly.NotFoundError, e:
                raise ValidationError('Server error: %s\nPlease contact the administrator in the contact page.' % e)
            subscription.currency = self.program.currency
            account = recurly.Account.get(self.subscriber.get_recurly_account_code())
            try:
                subscription.account = account
                try:
                    subscription.save()
                except recurly.ValidationError, e:
                    if e in ['already_subscribed: subscription.base You already have a subscription to this plan.']:
                        super(Subscription, self).save(*args, **kwargs)
                        return
            except recurly.BadRequestError, e:
                raise ValidationError('Server error: %s\nPlease contact the administrator in the contact page.' % e)
        return super(Subscription, self).save(*args, **kwargs)
    
    def get_progress_url(self):

apps/programs/forms.py
# programs/forms.py

from django import forms
from django.contrib.auth import authenticate
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import redirect
from django.forms.models import BaseInlineFormSet
from django.forms.models import inlineformset_factory

from users.forms import SubscriberFormMixin
from users.models import (HabitgramUser, BillingInfo)

from .models import (Habitgram, Subscription, SubscriptionTime)


class HabitgramForms(forms.ModelForm):
    action = reverse_lazy("program-create")
    submit_text = "Save Habitgram"
    program = None

    class Meta:
        model = Habitgram
        fields = ('title', 'description', 'image', 'message_type', 'message')


class SubscriptionForm(SubscriberFormMixin, forms.ModelForm):
    """
       A form to handle user-registration for a program
    """
    
    #cvv_number = forms.IntegerField(required=True, label="CVV Number",
    #                                max_value=9999,
    #                                widget=forms.TextInput(attrs={'size': '4'}))
    action = reverse_lazy('program-subscribe')
    submit_text = "Subscribe"

    class Meta:
        model = Subscription
        fields = tuple()
        extra = 1
    
    def clean(self):
        cleaned_data = super(SubscriptionForm, self).clean()
        cvv_number = cleaned_data.get('cvv_number')
        if len(str(cvv_number)) < 4:
            self._errors["cvv_number"] = self.error_class(["The verification number must be 4 digits."])
        return cleaned_data
    
    # def register_user_to_program(self, user, program):
    #     billing_info = BillingInfo.get_billing_info_by_user_id(user.id)
    #     if billing_info.cvv_number == self.data['cvv_number']:
    #         self.set_subscriber(user)
    #         new_subscription, created = Subscription.objects.get_or_create(
    #                                         program=program,
    #                                         subscriber=self.subscriber)
    #         if created:
    #             new_subscription.save()
    #         else:
    #             raise forms.ValidationError('You have already subscribed to this program')
    #         return redirect(self.get_success_url())
    #     else:
    #         return redirect(self.get_error_url())

templates/programs/auth_list.html
{% extends "programs/list.html" %}

{% block title %}My Created HabitGrams{% endblock %}

{% block heading %}
<h2>My Created HabitGrams</h2>
{% endblock %}

templates/programs/create.html
{% extends "base.html" %}

{% block title %}Create HabitGram{% endblock %}

{% block heading %}
<h2>Create HabitGram</h2>
{% endblock %}

{% block content %}
  {% include "util/form.html" %}
{% endblock %}

templates/programs/detail.html
{% extends "base.html" %}

{% block title %}HabitGram Details{% endblock %}

{% block content %}
	<div class="row">
		<!-- Second Band (Image Left with Text) -->
		<div class="row">
			<div class="large-6 columns">
				{% with habitgram as program %}
				<img src="{% include "programs/image_link.html" %}">
				{% endwith %}
			</div>
			<div class="large-6 columns">
				<h4>{{ habitgram.title }}</h4>
				{% if not form %}{% include "util/share.html" %}{% endif %}
				<br />
				<br />
				<br />
				<div>Author: {{habitgram.author}}</div>
				<div>Interactions: {{ habitgram.get_message_type_display }}</div>
				<br />
				<div class="right">
					{% if form %}
						<h3>Subscription Times:</h3>
						{% include "util/form.html" %}
						<br />
						<br />
					{% else %}
						{% if subscribed %}
							{% for sub_time in subscription.subscriptiontime_set.all %}
								<p>On {{ sub_time.get_weekday_display }} at {{sub_time.time}}</p>
							{% endfor %}
							<a href="{% url 'program-sub-update' subscription.id %}" class="button">Edit Subscription</a>
							<a href="{% url 'program-unsubscribe' habitgram.id %}" class="right button">Unsubscribe</a>
						{% else %}
							<a href="{% url 'program-subscribe' habitgram.id %}" class="right button">Sign me up!</a>
						{% endif %}
					{% endif %}
					<br />
					<a href="/getting-started/" class="right button">How do HabitGrams work?</a>
				</div>
			</div>
		</div>
		<!-- Third Band (Image Right with Text) -->
		<div class="row">
			<div class="large-8 columns">
				<br />
				<br />
				<div>{{ habitgram.description|default:"Unfortunately, this HabitGram does not yet have a description." }}</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/programs/edit.html
{% extends "base.html" %}

{% block title %}Edit HabitGram{% endblock %}

{% block heading %}
<h2>Edit HabitGram</h2>
{% endblock %}

{% block content %}
  {% include "util/form.html" %}
{% endblock %}

templates/programs/image_link.html
{% spaceless %}
{% if program.image and program.image.url %}
	{{ program.image.url }}
{% else %}
	{{ STATIC_URL }}images/default_habitgram_icon.jpg
{% endif %}
{% endspaceless %}

templates/programs/list.html
{% extends "base.html" %}

{% block title %}HabitGrams Catalog{% endblock %}

{% block heading %}
<h2>HabitGrams Catalog</h2>
{% endblock %}

{% block content %}
<div class="row">
  <div class="small-12 medium-12 large-12 columns medium-push-4 large-push-3">
    {% for program in programs %}
      <!-- Feed Entry -->
      <div class="row">
        <div class="small-3 large-2 columns"><img src="{% include "programs/image_link.html" %}" /></div>
        <div class="small-9 large-10 columns">
          <p><strong>{{ program.title }}:</strong> {{ program.description }}</p>
          <ul class="inline-list">
            <li><a class="button" href="{{ program.get_absolute_url }}">Details</a></li>
            <li><a class="button" href="{% url 'program-update' pk=program.id %}">Edit HabitGram</a></li>
            {% if program.subscribed %}
              <li><a class="button" href="{% url 'program-sub-update' pk=program.subscription.id %}">Edit Subscription</a></li>
              <li><a class="button" href="{% url 'program-unsubscribe' pk=program.id %}">Unsubscribe</a></li>
            {% else %}
              <li><a class="button" href="{{ program.get_subscription_url }}">Subscribe</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
      <!-- End Feed Entry -->
      <hr>
    {% empty %}
      <div class="row">
      <div class="small-9 large-5 columns">There doesn't appear to be any habitgrams here!</div>
      </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <br />
    <a href="{% url 'program-create' %}" class="button">Create New Habitgram</a>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/programs/sub_list.html
{% extends "programs/list.html" %}

{% block title %}My Subscribed HabitGrams{% endblock %}

{% block heading %}
<h2>My Subscribed HabitGrams</h2>
{% endblock %}